---
- name: '{{ ansible_name_module }} | file:state=directory | Ensure Archive directory exist '
  file:
    path: "{{ dir_bundle_location }}"
    state: directory
    recurse: true

- name: '{{ ansible_name_module }} | Mirror image registry | oc:adm:release:mirror'
  command: >
    oc adm release mirror \
    -a {{ ocp_registry_pull_secret_file }} \
     --from={{ ocp_release_image_registry}}/{{ ocp_release_image_repository }}:{{ocp_release_version }}-{{ ocp_release_arch }} \
     --to-dir={{ dir_bundle_location }} \
     --insecure=true
  register: catalog_mirrored

- name: '{{ ansible_name_module }} | Mirror image registry | oc:adm:release:mirror'
  git_url:
    url: "{{ rhcos_image_mirror_url | default('https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-4.7.7-x86_64-aws.x86_64.vmdk.gz') }}"
    dest: "{{ dir_bundle_location }}/"
    mode: '0666'
    force: yes
  register: ocp_rhcos_image_downloaded

- name: '{{ ansible_name_module }} | archive:xz | create artifactory image bundle '
  become: yes
  command: >
    tar -cvf {{ dir_bundle_location }}/{{ bundle_file_name | d('artifactory-bundle.tar.xz') }} \
     -C {{ dir_bundle_location }} .
  args:
    creates: "{{ dir_bundle_location }}/{{ bundle_file_name | d('artifactory-bundle.tar.xz') }}"
    warn: false
    chdir: "{{ dir_bundle_location }}/"
  when:
    - skip_bundle is undefined or not skip_bundle | bool
